# Generated by Django 4.2.9 on 2024-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
