# Generated by Django 4.2.9 on 2024-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_movie_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'ACTION'), ('adventure', 'ADVENTURE'), ('animation', 'ANIMATION'), ('biography', 'BIOGRAPHY'), ('comedy', 'COMEDY'), ('crime', 'CRIME'), ('cult movie', 'CULT MOVIE'), ('disney', 'DISNEY'), ('documentary', 'DOCUMENTARY'), ('drama', 'DRAMA'), ('erotic', 'EROTIC'), ('family', 'FAMILY'), ('fantasy', 'FANTASY'), ('film-noir', 'FILM-NOIR'), ('gangster', 'GANGSTER'), ('gay and lesbian', 'GAY AND LESBIAN'), ('history', 'HISTORY'), ('horror', 'HORROR'), ('military', 'MILITARY'), ('music', 'MUSIC'), ('musical', 'MUSICAL'), ('mystery', 'MYSTERY'), ('nature', 'NATURE'), ('neo-noir', 'NEO-NOIR'), ('period', 'PERIOD'), ('pixar', 'PIXAR'), ('road movie', 'ROAD MOVIE'), ('romance', 'ROMANCE'), ('sci-fi', 'SCI-FI'), ('short', 'SHORT'), ('spy', 'SPY'), ('super hero', 'SUPER HERO'), ('thriller', 'THRILLER'), ('visually stunning', 'VISUALLY STUNNING'), ('war', 'WAR'), ('western', 'WESTERN')], default='', max_length=50),
        ),
    ]
