# Generated by Django 4.2.9 on 2024-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
