# Generated by Django 4.2.9 on 2024-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_movie_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_poster_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
