# Generated by Django 4.2.9 on 2024-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_movie_image_poster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('movie', models.ManyToManyField(to='vote.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
