# Generated by Django 4.2.9 on 2024-03-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_user_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='John', max_length=50),
        ),
    ]
