# Generated by Django 4.2.9 on 2024-03-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
    ]
